apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: hotel-grafana
  namespace: hotel-dev
  labels:
    dashboards: grafana-a
spec:
  config:
    log:
      mode: console
      level: warn
    server:
      root_url: https://hotel-grafana-hotel-dev.apps.inholland.hcs-lab.nl
  deployment:
    spec:
      template:
        spec:
          containers:
            - name: grafana
              resources:
                requests:
                  cpu: 100m
                  memory: 128Mi
                limits:
                  cpu: 200m
                  memory: 256Mi
          volumes:
            - name: grafana-data
              emptyDir: {}
  dashboardLabelSelector:
    - matchLabels:
        dashboards: grafana-a