apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: hotel-grafana
  namespace: hotel-dev
  labels:
    dashboards: grafana-a
spec:
  config:
    log:
      mode: console
      level: warn
    server:
      root_url: https://hotel-grafana-hotel-dev.apps.inholland.hcs-lab.nl
    smtp:
      enabled: "true"
      host: "smtp.gmail.com:587"
      user: "${SMTP_USER}"
      password: "${SMTP_PASSWORD}"
      from_address: "${SMTP_USER}"
      from_name: "Grafana Alerts"
      startTLS_policy: "MandatoryStartTLS"
      skip_verify: "true"
  deployment:
    spec:
      template:
        spec:
          containers:
            - name: grafana
              env:
                - name: SMTP_USER
                  valueFrom:
                    secretKeyRef:
                      name: grafana-smtp-credentials
                      key: smtp-user
                - name: SMTP_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: grafana-smtp-credentials
                      key: smtp-password
              resources:
                requests:
                  cpu: 100m
                  memory: 128Mi
                limits:
                  cpu: 200m
                  memory: 256Mi
          volumes:
            - name: grafana-data
              emptyDir: {}
  dashboardLabelSelector:
    - matchLabels:
        dashboards: grafana-a