apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: hotel-dev
spec:
  limits:
    - default:
        cpu: "200m"
        memory: "256Mi"
      defaultRequest:
        cpu: "50m"
        memory: "128Mi"
      type: Container