apiVersion: monitoring.3scale.net/v1alpha1
kind: PrometheusExporter
metadata:
  name: quarkus-metrics-exporter
  namespace: hotel-dev
spec:
  type: prometheus
  image:
    name: quay.io/prometheuscommunity/prometheus
  port: 9090
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  endpoints:
    - interval: 15s
      path: /metrics
      targetPort: 8080
  selector:
    matchLabels:
      app: ptss-support-quarkus-base-repo